#server:
#  port: 9010
#spring:
#  application:
#    name: tensquare-friend #指定服务名
#  datasource:
#    driverClassName: com.mysql.jdbc.Driver
#    url: jdbc:mysql://192.168.66.128:3306/tensquare_friend?useUnicode=true&characterEncoding=utf-8&useSSL=false
#    username: root
#    password: 123456
#  jpa:
#    database: MySQL
#    show-sql: true
#jwt:
#  config:
#    key: zao
#
#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:6868/eureka
#  instance:
#    prefer-ip-address: true
#feign:
#  hystrix:
#    enabled: true